runtime: java
env: flex

env_variables:
  JAVA_OPTS: "-Dorg.apache.cxf.jaxws.checkPublishEndpointPermission=false"

handlers:
- url: /.*
  script: this field is required, but ignored

runtime_config:
   jdk: openjdk8
   server: jetty8